# Generated by Django 5.0.2 on 2026-02-19 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Seed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("variety", models.CharField(max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "Fruit"),
                            ("flower", "Flower"),
                            ("vegetable", "Vegetable"),
                            ("herb", "Herb"),
                            ("plant", "Plant"),
                            ("grain", "Grain"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "G"),
                            ("kg", "KG"),
                            ("seed", "Seed"),
                            ("pack", "Pack"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("date_collected", models.DateField()),
                ("best_before", models.DateField()),
                ("batch_number", models.CharField(max_length=255)),
                (
                    "collection_source",
                    models.CharField(
                        choices=[
                            ("self", "Self"),
                            ("friend", "Friend"),
                            ("family", "Family"),
                            ("bought", "Bought"),
                            ("gift", "Gift"),
                            ("farmers_market", "Farmers Market"),
                            ("garden_center", "Garden Center"),
                            ("local_harvesters", "Local Harvesters"),
                            ("online_market", "Online Market"),
                            ("other_market", "Other Market"),
                            ("home_harvest", "Home Harvest"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("supplier", models.CharField(max_length=255)),
                ("storage_location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
