# Generated by Django 6.0.2 on 2026-02-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed",
            name="qr_code",
            field=models.FileField(blank=True, upload_to="seed_qr/"),
        ),
        migrations.CreateModel(
            name="SeedPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="seed_photos/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="seeds.seed",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
