# Generated by Django 6.0.2 on 2026-02-28 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeds", "0002_seed_qr_code_seedphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SeedWishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("variety", models.CharField(blank=True, max_length=255)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fruit", "Fruit"),
                            ("flower", "Flower"),
                            ("vegetable", "Vegetable"),
                            ("herb", "Herb"),
                            ("plant", "Plant"),
                            ("grain", "Grain"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "preferred_source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("self", "Self"),
                            ("friend", "Friend"),
                            ("family", "Family"),
                            ("bought", "Bought"),
                            ("gift", "Gift"),
                            ("farmers_market", "Farmers Market"),
                            ("garden_center", "Garden Center"),
                            ("local_harvesters", "Local Harvesters"),
                            ("online_market", "Online Market"),
                            ("other_market", "Other Market"),
                            ("home_harvest", "Home Harvest"),
                            ("other", "Other"),
                        ],
                        max_length=255,
                    ),
                ),
                ("desired_quantity", models.PositiveIntegerField(default=1)),
                (
                    "desired_unit",
                    models.CharField(
                        choices=[
                            ("g", "G"),
                            ("kg", "KG"),
                            ("seed", "Seed"),
                            ("pack", "Pack"),
                            ("other", "Other"),
                        ],
                        default="pack",
                        max_length=255,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("acquired", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["acquired", "-created_at"],
            },
        ),
    ]
