# Generated by Django 6.0.2 on 2026-02-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeds", "0003_seedwishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="seedwishlist",
            name="acquired_seed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wishlist_acquisitions",
                to="seeds.seed",
            ),
        ),
    ]
