# Generated by Django 6.0.2 on 2026-02-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("seeds", "0004_seedwishlist_acquired_seed"),
    ]

    operations = [
        migrations.AddField(
            model_name="seed",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name="seedwishlist",
            name="follow_up_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
