# Generated by Django 6.0.2 on 2026-03-02 16:08

from django.conf import settings
from django.db import migrations, models


def fix_seed_best_before_dates(apps, schema_editor):
    Seed = apps.get_model("seeds", "Seed")
    for seed in Seed.objects.filter(best_before__lt=models.F("date_collected")).only(
        "id", "best_before", "date_collected"
    ):
        seed.best_before = seed.date_collected
        seed.save(update_fields=["best_before"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("seeds", "0005_seed_low_stock_threshold_seedwishlist_follow_up_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="seed",
            index=models.Index(
                fields=["user", "best_before"], name="seed_user_best_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seed",
            index=models.Index(fields=["user", "category"], name="seed_user_cat_idx"),
        ),
        migrations.AddIndex(
            model_name="seed",
            index=models.Index(
                fields=["user", "collection_source"], name="seed_user_src_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seed",
            index=models.Index(
                fields=["user", "created_at"], name="seed_user_created_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seedwishlist",
            index=models.Index(fields=["user", "acquired"], name="wish_user_acq_idx"),
        ),
        migrations.AddIndex(
            model_name="seedwishlist",
            index=models.Index(
                fields=["user", "follow_up_date"], name="wish_user_follow_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="seedwishlist",
            index=models.Index(fields=["user", "priority"], name="wish_user_prio_idx"),
        ),
        migrations.RunPython(fix_seed_best_before_dates, reverse_code=noop_reverse),
        migrations.AddConstraint(
            model_name="seed",
            constraint=models.CheckConstraint(
                condition=models.Q(("best_before__gte", models.F("date_collected"))),
                name="seed_best_before_gte_collected",
            ),
        ),
    ]
