# Generated by Django 6.0.2 on 2026-03-02 16:44

import django.db.models.deletion
from django.db import migrations, models


def backfill_seed_batches(apps, schema_editor):
    Seed = apps.get_model("seeds", "Seed")
    SeedBatch = apps.get_model("seeds", "SeedBatch")

    for seed in Seed.objects.all().iterator():
        SeedBatch.objects.get_or_create(
            seed_id=seed.id,
            batch_number=seed.batch_number,
            defaults={
                "quantity": seed.quantity,
                "low_stock_threshold": seed.low_stock_threshold,
                "unit": seed.unit,
                "date_collected": seed.date_collected,
                "best_before": seed.best_before,
                "collection_source": seed.collection_source,
                "supplier": seed.supplier,
                "storage_location": seed.storage_location,
                "notes": seed.notes or "",
                "qr_code": seed.qr_code,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0006_seed_seed_user_best_idx_seed_seed_user_cat_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeedBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('unit', models.CharField(choices=[('g', 'G'), ('kg', 'KG'), ('seed', 'Seed'), ('pack', 'Pack'), ('other', 'Other')], max_length=255)),
                ('date_collected', models.DateField()),
                ('best_before', models.DateField()),
                ('batch_number', models.CharField(max_length=255)),
                ('collection_source', models.CharField(choices=[('self', 'Self'), ('friend', 'Friend'), ('family', 'Family'), ('bought', 'Bought'), ('gift', 'Gift'), ('farmers_market', 'Farmers Market'), ('garden_center', 'Garden Center'), ('local_harvesters', 'Local Harvesters'), ('online_market', 'Online Market'), ('other_market', 'Other Market'), ('home_harvest', 'Home Harvest'), ('other', 'Other')], max_length=255)),
                ('supplier', models.CharField(max_length=255)),
                ('storage_location', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('qr_code', models.FileField(blank=True, upload_to='seed_qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='seeds.seed')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['seed', 'best_before'], name='batch_seed_best_idx'), models.Index(fields=['seed', 'created_at'], name='batch_seed_created_idx'), models.Index(fields=['batch_number'], name='batch_number_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('best_before__gte', models.F('date_collected'))), name='batch_best_before_gte_collected'), models.UniqueConstraint(fields=('seed', 'batch_number'), name='uniq_seed_batch_number')],
            },
        ),
        migrations.RunPython(backfill_seed_batches, reverse_code=noop_reverse),
    ]
