# Generated by Django 6.0.2 on 2026-03-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seeds', '0007_seedbatch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seed',
            name='seed_best_before_gte_collected',
        ),
        migrations.RemoveIndex(
            model_name='seed',
            name='seed_user_best_idx',
        ),
        migrations.RemoveIndex(
            model_name='seed',
            name='seed_user_src_idx',
        ),
        migrations.RemoveField(
            model_name='seedbatch',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='seedbatch',
            name='unit',
        ),
        migrations.AlterField(
            model_name='seedbatch',
            name='storage_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RemoveField(
            model_name='seed',
            name='batch_number',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='best_before',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='collection_source',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='date_collected',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='low_stock_threshold',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='storage_location',
        ),
        migrations.RemoveField(
            model_name='seed',
            name='supplier',
        ),
    ]
